-- GoldenGate MCP Server — Oracle setup DDL
--
-- Run this script once against the Oracle replica as a DBA user
-- before starting the MCP server.
--
-- Sections:
--   1. Read-only application user
--   2. AUDIT_LOG table (required when AUDIT_LOG_MODE=oracle)

-- ==================================================================
-- 1. Read-only application user
-- ==================================================================
-- Create the MCP reader account (adjust tablespace / profile as needed).
-- The password set here must match ORACLE_PASSWORD in your .env file.

CREATE USER mcp_reader IDENTIFIED BY "changeme"
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON users;

-- Grant connect only — never resource or DBA
GRANT CREATE SESSION TO mcp_reader;

-- Read access on all business tables queried by the MCP server.
-- Extend this list when new entities are added to schema_map.yaml.
GRANT SELECT ON BANKING.CUSTOMER_MASTER  TO mcp_reader;
GRANT SELECT ON BANKING.ACCOUNT_MASTER   TO mcp_reader;
GRANT SELECT ON BANKING.TRANSACTION_LOG  TO mcp_reader;
GRANT SELECT ON BANKING.GL_BALANCE       TO mcp_reader;
GRANT SELECT ON BANKING.ALERT_QUEUE      TO mcp_reader;

-- INSERT on AUDIT_LOG is required when AUDIT_LOG_MODE=oracle.
-- (Read access is not required — the server only writes.)
GRANT INSERT ON AUDIT_LOG TO mcp_reader;


-- ==================================================================
-- 2. AUDIT_LOG table
-- ==================================================================
-- Required only when AUDIT_LOG_MODE=oracle.
-- This is an infrastructure table; it is NOT managed via schema_map.yaml.
-- DDL is idempotent — safe to re-run.

CREATE TABLE AUDIT_LOG (
    ID            NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TOOL_NAME     VARCHAR2(100) NOT NULL,
    CALLER_ID     VARCHAR2(200) NOT NULL,
    TIMESTAMP_UTC TIMESTAMP     NOT NULL,
    INPUT_HASH    VARCHAR2(64)  NOT NULL,   -- SHA-256 hex of input payload
    OUTPUT_HASH   VARCHAR2(64)  NOT NULL,   -- SHA-256 hex of output payload
    LATENCY_MS    NUMBER(10, 3) NOT NULL,
    DECISION      VARCHAR2(200)             -- nullable
);

-- Index for time-range queries (e.g. compliance lookbacks)
CREATE INDEX AUDIT_LOG_TS_IDX ON AUDIT_LOG (TIMESTAMP_UTC);

-- Index for per-tool reporting
CREATE INDEX AUDIT_LOG_TOOL_IDX ON AUDIT_LOG (TOOL_NAME);

COMMIT;
